import { createFileRoute } from "@tanstack/react-router";
import {
  DollarSign, TrendingUp, Wallet, AlertTriangle, Users, ShoppingCart,
  Activity, Sparkles,
} from "lucide-react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line,
  LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import { PageHeader, Panel, RiskBadge, StatCard } from "@/components/primitives";
import { ALERTS, CASHFLOW, DEPARTMENTS, REVENUE, TRANSACTIONS } from "@/lib/mock";

export const Route = createFileRoute("/_app/")({
  component: CommandCenter,
});

function CommandCenter() {
  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Finance Command Center"
        title="Welcome back, Amara"
        subtitle="Live financial intelligence across Nova Holdings. Updated 12 seconds ago."
        actions={
          <>
            <button className="px-4 py-2 rounded-full glass text-sm flex items-center gap-2 hover:translate-y-[-1px] transition">
              <Activity className="size-4" /> Live mode
            </button>
            <button className="px-4 py-2 rounded-full bg-primary text-primary-foreground text-sm flex items-center gap-2 glow">
              <Sparkles className="size-4" /> AI summary
            </button>
          </>
        }
      />

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard label="Revenue (YTD)" value={3274000} prefix="$" delta={18} icon={DollarSign} />
        <StatCard label="Expenses (YTD)" value={1801000} prefix="$" delta={6} icon={Wallet} />
        <StatCard label="Net cash flow" value={1473000} prefix="$" delta={24} icon={TrendingUp} />
        <StatCard label="Pending approvals" value={17} delta={-12} icon={AlertTriangle} />
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        <Panel
          title="Revenue vs Expenses"
          subtitle="Last 12 months"
          className="xl:col-span-2"
          action={<Legendish />}
        >
          <div className="h-[280px]">
            <ResponsiveContainer>
              <AreaChart data={REVENUE}>
                <defs>
                  <linearGradient id="g1" x1="0" x2="0" y1="0" y2="1">
                    <stop offset="0%" stopColor="var(--primary)" stopOpacity={0.55} />
                    <stop offset="100%" stopColor="var(--primary)" stopOpacity={0} />
                  </linearGradient>
                  <linearGradient id="g2" x1="0" x2="0" y1="0" y2="1">
                    <stop offset="0%" stopColor="var(--accent)" stopOpacity={0.45} />
                    <stop offset="100%" stopColor="var(--accent)" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="m" tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={tipStyle} />
                <Area type="monotone" dataKey="revenue" stroke="var(--primary)" fill="url(#g1)" strokeWidth={2} />
                <Area type="monotone" dataKey="expenses" stroke="var(--accent)" fill="url(#g2)" strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </Panel>

        <Panel title="AI insights" subtitle="Auto-generated by Copilot">
          <div className="space-y-2.5">
            {ALERTS.map((a, i) => (
              <div key={i} className="flex items-start gap-3 p-3 rounded-xl bg-muted/40 hover:bg-muted/70 transition">
                <div
                  className={`size-8 shrink-0 rounded-lg grid place-items-center ${
                    a.level === "danger" ? "bg-destructive/20 text-destructive"
                    : a.level === "warn" ? "bg-warning/20 text-warning"
                    : "bg-primary/20 text-primary"
                  }`}
                >
                  <Sparkles className="size-4" />
                </div>
                <div className="text-sm leading-snug">{a.text}</div>
              </div>
            ))}
          </div>
        </Panel>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        <Panel title="Cash flow" subtitle="Net inflow over 12 months">
          <div className="h-[220px]">
            <ResponsiveContainer>
              <LineChart data={CASHFLOW}>
                <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="m" tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={tipStyle} />
                <Line type="monotone" dataKey="net" stroke="var(--neon)" strokeWidth={3} dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </Panel>

        <Panel title="Department spend" subtitle="This quarter (in $K)">
          <div className="h-[220px]">
            <ResponsiveContainer>
              <BarChart data={DEPARTMENTS}>
                <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="name" tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={tipStyle} />
                <Bar dataKey="spend" radius={[8, 8, 0, 0]}>
                  {DEPARTMENTS.map((_, i) => (
                    <Cell key={i} fill={i % 2 ? "var(--accent)" : "var(--primary)"} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Panel>

        <Panel title="Live activity" subtitle="Realtime org-wide events">
          <ul className="space-y-2 text-sm">
            {[
              { i: ShoppingCart, t: "PO #PR-1187 approved", who: "Procurement", w: "now" },
              { i: Users, t: "248 employees included in payroll batch", who: "HR", w: "1m" },
              { i: AlertTriangle, t: "Tax inconsistency flagged on TXN-9817", who: "AI", w: "3m" },
              { i: TrendingUp, t: "Q3 forecast updated (+2.1%)", who: "Finance", w: "6m" },
              { i: DollarSign, t: "Payment cleared: Helix Supplies", who: "Bank", w: "9m" },
            ].map((e, i) => (
              <li key={i} className="flex items-center gap-3 p-2 rounded-lg hover:bg-muted/60 transition">
                <div className="size-8 grid place-items-center rounded-lg bg-primary/15 text-primary">
                  <e.i className="size-4" />
                </div>
                <div className="flex-1">
                  <div className="leading-tight">{e.t}</div>
                  <div className="text-[11px] text-muted-foreground">{e.who}</div>
                </div>
                <div className="text-[11px] text-muted-foreground">{e.w}</div>
              </li>
            ))}
          </ul>
        </Panel>
      </div>

      <Panel title="Live transactions" subtitle="With AI risk scoring">
        <div className="overflow-x-auto -mx-2">
          <table className="w-full text-sm">
            <thead className="text-xs text-muted-foreground">
              <tr className="[&>th]:text-left [&>th]:font-medium [&>th]:px-3 [&>th]:py-2">
                <th>ID</th><th>Counterparty</th><th>Type</th><th className="!text-right">Amount</th><th>Risk</th><th>Status</th><th>Time</th>
              </tr>
            </thead>
            <tbody>
              {TRANSACTIONS.map((t) => (
                <tr key={t.id} className="border-t border-border/40 hover:bg-muted/40 transition">
                  <td className="px-3 py-2.5 font-mono text-xs text-muted-foreground">{t.id}</td>
                  <td className="px-3 py-2.5 font-medium">{t.party}</td>
                  <td className="px-3 py-2.5 text-muted-foreground">{t.type}</td>
                  <td className="px-3 py-2.5 text-right tabular-nums">${t.amount.toLocaleString()}</td>
                  <td className="px-3 py-2.5"><RiskBadge score={t.risk} /></td>
                  <td className="px-3 py-2.5">
                    <span className={`text-[11px] px-2 py-0.5 rounded-full ${
                      t.status === "cleared" ? "bg-success/15 text-success"
                      : t.status === "review" ? "bg-warning/15 text-warning"
                      : "bg-destructive/15 text-destructive"
                    }`}>{t.status}</span>
                  </td>
                  <td className="px-3 py-2.5 text-muted-foreground text-xs">{t.time}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>
    </div>
  );
}

const tipStyle = {
  background: "var(--popover)", border: "1px solid var(--border)",
  borderRadius: 12, fontSize: 12, color: "var(--popover-foreground)",
};

function Legendish() {
  return (
    <div className="flex gap-3 text-xs text-muted-foreground">
      <span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-primary" /> Revenue</span>
      <span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-accent" /> Expenses</span>
    </div>
  );
}