/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRiskRouteImport } from './routes/_app.risk'
import { Route as AppOrgMapRouteImport } from './routes/_app.org-map'
import { Route as AppCollaborationRouteImport } from './routes/_app.collaboration'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgMapRoute = AppOrgMapRouteImport.update({
  id: '/org-map',
  path: '/org-map',
  getParentRoute: () => AppRoute,
} as any)
const AppCollaborationRoute = AppCollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/collaboration': typeof AppCollaborationRoute
  '/org-map': typeof AppOrgMapRoute
  '/risk': typeof AppRiskRoute
}
export interface FileRoutesByTo {
  '/collaboration': typeof AppCollaborationRoute
  '/org-map': typeof AppOrgMapRoute
  '/risk': typeof AppRiskRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/collaboration': typeof AppCollaborationRoute
  '/_app/org-map': typeof AppOrgMapRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collaboration' | '/org-map' | '/risk'
  fileRoutesByTo: FileRoutesByTo
  to: '/collaboration' | '/org-map' | '/risk' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/collaboration'
    | '/_app/org-map'
    | '/_app/risk'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org-map': {
      id: '/_app/org-map'
      path: '/org-map'
      fullPath: '/org-map'
      preLoaderRoute: typeof AppOrgMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collaboration': {
      id: '/_app/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof AppCollaborationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCollaborationRoute: typeof AppCollaborationRoute
  AppOrgMapRoute: typeof AppOrgMapRoute
  AppRiskRoute: typeof AppRiskRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCollaborationRoute: AppCollaborationRoute,
  AppOrgMapRoute: AppOrgMapRoute,
  AppRiskRoute: AppRiskRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
